version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yup
    versions:
    - 0.32.8
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: react-avatar
    versions:
    - 3.9.7
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
